server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: customer_route
          uri: http://localhost:9090/
          predicates:
            - Path=/api/v1/customers/**
        - id: vehicle_route
          uri: http://localhost:9091/
          predicates:
            - Path=/api/v1/vehicles/**
        - id: payment_route
          uri: http://localhost:9092/
          predicates:
            - Path=/api/v1/payments/**
        - id: rental_route
          uri: http://localhost:9093/
          predicates:
            - Path=/api/v1/rentals/**
        - id: reservation_route
          uri: http://localhost:9094/
          predicates:
            - Path=/api/v1/reservations/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

